/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Player, Formation, PositionCategory } from "./types";

export const CATEGORIES: PositionCategory[] = ["Tor", "Abwehr", "Mittelfeld", "Sturm", "Trainer"];

const CLUB_LOGO_MAP: Record<string, string> = {
  "Young Boys": "https://logo.clearbit.com/bscyb.ch",
  "Luzern": "https://logo.clearbit.com/fcl.ch",
  "Sion": "https://logo.clearbit.com/fc-sion.ch",
  "Grasshopper": "https://logo.clearbit.com/gcz.ch",
  "Grasshopper Club": "https://logo.clearbit.com/gcz.ch",
  "FC Winterthur": "https://logo.clearbit.com/fcwinterthur.ch",
  "Winterthur": "https://logo.clearbit.com/fcwinterthur.ch",
  "Lausanne-Sport": "https://logo.clearbit.com/lausanne-sport.ch",
  "Thun": "https://logo.clearbit.com/fcthun.ch",
  "FC Thun": "https://logo.clearbit.com/fcthun.ch",
  "St. Gallen": "https://logo.clearbit.com/fcsg.ch",
  "Servette FC": "https://logo.clearbit.com/servettefc.ch",
  "Basel": "https://logo.clearbit.com/fcb.ch",
  "FC Basel": "https://logo.clearbit.com/fcb.ch",
  "Zürich": "https://logo.clearbit.com/fcz.ch",
  "FC Zürich": "https://logo.clearbit.com/fcz.ch",
  "Lugano": "https://logo.clearbit.com/fclugano.com",
};

const CLUB_DOMAIN_MAP: Record<string, string> = {
  "Young Boys": "bscyb.ch",
  "Luzern": "fcl.ch",
  "Sion": "fc-sion.ch",
  "Grasshopper": "gcz.ch",
  "Grasshopper Club": "gcz.ch",
  "FC Winterthur": "fcwinterthur.ch",
  "Winterthur": "fcwinterthur.ch",
  "Lausanne-Sport": "lausanne-sport.ch",
  "Thun": "fcthun.ch",
  "FC Thun": "fcthun.ch",
  "St. Gallen": "fcsg.ch",
  "Servette FC": "servettefc.ch",
  "Basel": "fcb.ch",
  "FC Basel": "fcb.ch",
  "Zürich": "fcz.ch",
  "FC Zürich": "fcz.ch",
  "Lugano": "fclugano.com",
};

export const INITIAL_PLAYERS: Player[] = [
  { id: "p1", name: "Marvin Keller", category: "Tor", club: "Young Boys" },
  { id: "p2", name: "Pascal Loretz", category: "Tor", club: "Luzern" },
  { id: "p3", name: "Anthony Racioppi", category: "Tor", club: "Sion" },
  { id: "p4", name: "Justin Hammel", category: "Tor", club: "Grasshopper" },
  { id: "p5", name: "Stefanos Kapino", category: "Tor", club: "FC Winterthur" },
  { id: "p6", name: "Numa Lavanchy", category: "Abwehr", club: "Sion" },
  { id: "p7", name: "Karlo Letica", category: "Tor", club: "Lausanne-Sport" },
  { id: "p8", name: "Nias Hefti", category: "Abwehr", club: "Sion" },
  { id: "p9", name: "Tyron Owusu", category: "Mittelfeld", club: "Luzern" },
  { id: "p10", name: "Matteo Di Giusto", category: "Mittelfeld", club: "Luzern" },
  { id: "p11", name: "Jan Kronig", category: "Abwehr", club: "Sion" },
  { id: "p12", name: "Niklas Steffen", category: "Tor", club: "Thun" },
  { id: "p13", name: "Anto Grgić", category: "Mittelfeld", club: "Lugano" },
  { id: "p14", name: "Lawrence Ati-Zigi", category: "Tor", club: "St. Gallen" },
  { id: "p15", name: "Carlo Boukhalfa", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p16", name: "Miroslav Stevanović", category: "Mittelfeld", club: "Servette FC" },
  { id: "p17", name: "Kevin Mouanga", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p18", name: "Ali Kabacalman", category: "Mittelfeld", club: "Sion" },
  { id: "p19", name: "Kreshnik Hajrizi", category: "Abwehr", club: "Sion" },
  { id: "p20", name: "Marwin Hitz", category: "Tor", club: "Basel" },
  { id: "p21", name: "Dominik Schmid", category: "Abwehr", club: "Basel" },
  { id: "p22", name: "Chima Okoroji", category: "Abwehr", club: "St. Gallen" },
  { id: "p23", name: "Antonios Papadopoulos", category: "Abwehr", club: "Lugano" },
  { id: "p24", name: "Leonardo Bertone", category: "Mittelfeld", club: "Thun" },
  { id: "p25", name: "Ylyas Chouaref", category: "Mittelfeld", club: "Sion" },
  { id: "p26", name: "Loris Benito", category: "Abwehr", club: "Young Boys" },
  { id: "p27", name: "Uran Bislimi", category: "Mittelfeld", club: "Lugano" },
  { id: "p28", name: "Steve Rouiller", category: "Abwehr", club: "Servette FC" },
  { id: "p29", name: "Adrian Bajrami", category: "Abwehr", club: "Luzern" },
  { id: "p30", name: "Hugo Vandermersch", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p31", name: "Jozo Stanić", category: "Abwehr", club: "St. Gallen" },
  { id: "p32", name: "Rilind Nivokazi", category: "Sturm", club: "Sion" },
  { id: "p33", name: "Timothé Cognat", category: "Mittelfeld", club: "Servette FC" },
  { id: "p34", name: "Bung Meng Freimann", category: "Abwehr", club: "Luzern" },
  { id: "p35", name: "Marco Bürki", category: "Abwehr", club: "Thun" },
  { id: "p36", name: "Jonathan Asp Jensen", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p37", name: "Lindrit Kamberi", category: "Abwehr", club: "Zürich" },
  { id: "p38", name: "Léo Leroy", category: "Mittelfeld", club: "Basel" },
  { id: "p39", name: "Elmin Rastoder", category: "Sturm", club: "Thun" },
  { id: "p40", name: "Dirk Abels", category: "Abwehr", club: "Grasshopper" },
  { id: "p41", name: "Lars Lukas Mai", category: "Abwehr", club: "Lugano" },
  { id: "p42", name: "Pius Dorn", category: "Abwehr", club: "Luzern" },
  { id: "p43", name: "Cheveyo Tsawa", category: "Mittelfeld", club: "Zürich" },
  { id: "p44", name: "Tom Gaal", category: "Abwehr", club: "St. Gallen" },
  { id: "p45", name: "Taisei Abe", category: "Mittelfeld", club: "Luzern" },
  { id: "p46", name: "Philippe Keny", category: "Sturm", club: "Zürich" },
  { id: "p47", name: "Nelson Palacio", category: "Mittelfeld", club: "Zürich" },
  { id: "p48", name: "Yanis Cimignani", category: "Mittelfeld", club: "Lugano" },
  { id: "p49", name: "Baltazar", category: "Mittelfeld", club: "Sion" },
  { id: "p50", name: "Jan Bamert", category: "Abwehr", club: "Thun" },
  { id: "p51", name: "Michael Heule", category: "Abwehr", club: "Thun" },
  { id: "p52", name: "Lukas Görtler", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p53", name: "Lilian Njoh", category: "Abwehr", club: "Servette FC" },
  { id: "p54", name: "Mattia Zanotti", category: "Abwehr", club: "Lugano" },
  { id: "p55", name: "Andrin Hunziker", category: "Sturm", club: "FC Winterthur" },
  { id: "p56", name: "Simone Stroscio", category: "Abwehr", club: "Grasshopper" },
  { id: "p57", name: "Olivier Custodio", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p58", name: "Karim Sow", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p59", name: "Xherdan Shaqiri", category: "Mittelfeld", club: "Basel" },
  { id: "p60", name: "Bradley Mazikou", category: "Abwehr", club: "Servette FC" },
  { id: "p61", name: "Brandon Soppy", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p62", name: "Joël Mall", category: "Tor", club: "Servette FC" },
  { id: "p63", name: "Nicolas Vouilloz", category: "Abwehr", club: "Basel" },
  { id: "p64", name: "Christian Fassnacht", category: "Mittelfeld", club: "Young Boys" },
  { id: "p65", name: "Flavius Daniliuc", category: "Abwehr", club: "Basel" },
  { id: "p66", name: "Sandro Lauper", category: "Mittelfeld", club: "Young Boys" },
  { id: "p67", name: "Alessandro Vogt", category: "Sturm", club: "St. Gallen" },
  { id: "p68", name: "Remo Arnold", category: "Abwehr", club: "FC Winterthur" },
  { id: "p69", name: "Metinho", category: "Mittelfeld", club: "Basel" },
  { id: "p70", name: "Aliou Badara Baldé", category: "Sturm", club: "St. Gallen" },
  { id: "p71", name: "Kevin Behrens", category: "Sturm", club: "Lugano" },
  { id: "p72", name: "David Douline", category: "Mittelfeld", club: "Servette FC" },
  { id: "p73", name: "Gaoussou Diakite", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p74", name: "Alexandre Jankewitz", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p75", name: "Fabio Fehr", category: "Abwehr", club: "Thun" },
  { id: "p76", name: "Théo Golliard", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p77", name: "Jamie Roche", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p78", name: "Luca Zuffi", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p79", name: "Armin Gigovic", category: "Mittelfeld", club: "Young Boys" },
  { id: "p80", name: "Lovro Zvonarek", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p81", name: "Edimilson Fernandes", category: "Mittelfeld", club: "Young Boys" },
  { id: "p82", name: "Amir Saipi", category: "Tor", club: "Lugano" },
  { id: "p83", name: "Yanick Brecher", category: "Tor", club: "Zürich" },
  { id: "p84", name: "Lukas Daschner", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p85", name: "Bénie Traoré", category: "Sturm", club: "Basel" },
  { id: "p86", name: "Silvan Sidler", category: "Abwehr", club: "FC Winterthur" },
  { id: "p87", name: "Brighton Labeau", category: "Sturm", club: "Thun" },
  { id: "p88", name: "Mattias Käit", category: "Mittelfeld", club: "Thun" },
  { id: "p89", name: "Imourane Hassane", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p90", name: "Joel Monteiro", category: "Mittelfeld", club: "Young Boys" },
  { id: "p91", name: "Renato Steffen", category: "Sturm", club: "Lugano" },
  { id: "p92", name: "Chris Bedia", category: "Sturm", club: "Young Boys" },
  { id: "p93", name: "Morgan Poaty", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p94", name: "Christian Witzig", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p95", name: "Tim Meyer", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p96", name: "Lamine Fomba", category: "Mittelfeld", club: "Servette FC" },
  { id: "p97", name: "Florian Ayé", category: "Sturm", club: "Servette FC" },
  { id: "p98", name: "Stefan Knežević", category: "Abwehr", club: "Luzern" },
  { id: "p99", name: "Alvyn Sanches", category: "Mittelfeld", club: "Young Boys" },
  { id: "p100", name: "Gregory Wüthrich", category: "Abwehr", club: "Young Boys" },
  { id: "p101", name: "Daniel Correia", category: "Mittelfeld", club: "Lugano" },
  { id: "p102", name: "Lucas Ferreira", category: "Mittelfeld", club: "Luzern" },
  { id: "p103", name: "Randy Schneider", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p104", name: "Genís Montolio", category: "Abwehr", club: "Thun" },
  { id: "p105", name: "Luke Plange", category: "Sturm", club: "Grasshopper" },
  { id: "p106", name: "Franz-Ethan Meichtry", category: "Mittelfeld", club: "Thun" },
  { id: "p107", name: "Nathan Butler-Oyedeji", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p108", name: "Beyatt Lekoueiry", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p109", name: "Saidy Janko", category: "Abwehr", club: "Young Boys" },
  { id: "p110", name: "Sékou Fofana", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p111", name: "Albian Ajeti", category: "Sturm", club: "Basel" },
  { id: "p112", name: "Bledian Krasniqi", category: "Mittelfeld", club: "Zürich" },
  { id: "p113", name: "Steven Zuber", category: "Mittelfeld", club: "Zürich" },
  { id: "p114", name: "Christopher Ibayi", category: "Sturm", club: "Thun" },
  { id: "p115", name: "Valmir Matoshi", category: "Mittelfeld", club: "Thun" },
  { id: "p116", name: "Alan Virginius", category: "Mittelfeld", club: "Young Boys" },
  { id: "p117", name: "Matthias Phaeton", category: "Sturm", club: "Zürich" },
  { id: "p118", name: "Oscar Kabwit", category: "Sturm", club: "Luzern" },
  { id: "p119", name: "Martim Marques", category: "Abwehr", club: "Lugano" },
  { id: "p120", name: "Ruben Dantas Fernandes", category: "Abwehr", club: "Luzern" },
  { id: "p121", name: "Ilan Sauter", category: "Abwehr", club: "Zürich" },
  { id: "p122", name: "Justin Roth", category: "Mittelfeld", club: "Thun" },
  { id: "p123", name: "Mohamed Haj Mahmoud", category: "Mittelfeld", club: "Lugano" },
  { id: "p124", name: "Behar Neziri", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p125", name: "Livano Comenencia", category: "Abwehr", club: "Zürich" },
  { id: "p126", name: "Theo Bair", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p127", name: "Georgios Koutsias", category: "Sturm", club: "Lugano" },
  { id: "p128", name: "Kastriot Imeri", category: "Mittelfeld", club: "Thun" },
  { id: "p129", name: "Théo Berdayes", category: "Mittelfeld", club: "Sion" },
  { id: "p130", name: "Julian von Moos", category: "Sturm", club: "Luzern" },
  { id: "p131", name: "Souleymane Diaby", category: "Abwehr", club: "FC Winterthur" },
  { id: "p132", name: "Cyrill May", category: "Abwehr", club: "St. Gallen" },
  { id: "p133", name: "Marco Burch", category: "Abwehr", club: "Servette FC" },
  { id: "p134", name: "Pajtim Kasami", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p135", name: "Nicky Beloko", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p136", name: "Nils Reichmuth", category: "Mittelfeld", club: "Thun" },
  { id: "p137", name: "Adrian Durrer", category: "Abwehr", club: "FC Winterthur" },
  { id: "p138", name: "Josias Lukembila", category: "Mittelfeld", club: "Sion" },
  { id: "p139", name: "Rayan Raveloson", category: "Mittelfeld", club: "Young Boys" },
  { id: "p140", name: "Stéphane Cueni", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p141", name: "Liam Chipperfield", category: "Mittelfeld", club: "Sion" },
  { id: "p142", name: "Abdoulaye Diaby", category: "Abwehr", club: "Grasshopper" },
  { id: "p143", name: "Silas Huber", category: "Tor", club: "Zürich" },
  { id: "p144", name: "David von Ballmoos", category: "Tor", club: "Lugano" },
  { id: "p145", name: "Philip Otele", category: "Mittelfeld", club: "Basel" },
  { id: "p146", name: "David Vujevic", category: "Abwehr", club: "Zürich" },
  { id: "p147", name: "Adrian Grbić", category: "Sturm", club: "Luzern" },
  { id: "p148", name: "Mariano Gómez", category: "Abwehr", club: "Zürich" },
  { id: "p149", name: "Andrej Bačanin", category: "Mittelfeld", club: "Basel" },
  { id: "p150", name: "Benjamin Kololli", category: "Mittelfeld", club: "Sion" },
  { id: "p151", name: "Samuel Krasniqi", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p152", name: "Noé Sow", category: "Abwehr", club: "Sion" },
  { id: "p153", name: "Lucien Dähler", category: "Abwehr", club: "Thun" },
  { id: "p154", name: "Keigo Tsunemoto", category: "Abwehr", club: "Basel" },
  { id: "p155", name: "Bafodé Dansoko", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p156", name: "Samuel Marques", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p157", name: "Jonas Adjetey", category: "Abwehr", club: "Basel" },
  { id: "p158", name: "Ibrahim Salah", category: "Mittelfeld", club: "Basel" },
  { id: "p159", name: "Jaouen Hadjam", category: "Abwehr", club: "Young Boys" },
  { id: "p160", name: "Umeh Emmanuel", category: "Mittelfeld", club: "Zürich" },
  { id: "p161", name: "Dylan Bronn", category: "Abwehr", club: "Servette FC" },
  { id: "p162", name: "Samuel Mráz", category: "Sturm", club: "Servette FC" },
  { id: "p163", name: "Tibault Citherlet", category: "Abwehr", club: "FC Winterthur" },
  { id: "p164", name: "Florent Mollet", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p165", name: "Koba Koindredi", category: "Mittelfeld", club: "Basel" },
  { id: "p166", name: "Mouhamed El Bachir Ngom", category: "Abwehr", club: "Grasshopper" },
  { id: "p167", name: "Óscar Clemente", category: "Sturm", club: "Grasshopper" },
  { id: "p168", name: "Gabriel Sigua", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p169", name: "Lars Villiger", category: "Sturm", club: "Luzern" },
  { id: "p170", name: "Jérémy Guillemenot", category: "Sturm", club: "Servette FC" },
  { id: "p171", name: "Damienus Reverson", category: "Sturm", club: "Zürich" },
  { id: "p172", name: "Hannes Delcroix", category: "Abwehr", club: "Lugano" },
  { id: "p173", name: "Darian Males", category: "Mittelfeld", club: "Young Boys" },
  { id: "p174", name: "Kevin Rüegg", category: "Abwehr", club: "Basel" },
  { id: "p175", name: "Omar Janneh", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p176", name: "Kevin Spadanuda", category: "Mittelfeld", club: "Luzern" },
  { id: "p177", name: "Nishan Burkart", category: "Sturm", club: "FC Winterthur" },
  { id: "p178", name: "Alexander Hack", category: "Abwehr", club: "Zürich" },
  { id: "p179", name: "Miguel Reichmuth", category: "Mittelfeld", club: "Zürich" },
  { id: "p180", name: "Junior Kadile", category: "Mittelfeld", club: "Servette FC" },
  { id: "p181", name: "Fabian Rohner", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p182", name: "Sven Köhler", category: "Abwehr", club: "Grasshopper" },
  { id: "p183", name: "Luka Mikulić", category: "Abwehr", club: "Grasshopper" },
  { id: "p184", name: "Lukas Mühl", category: "Abwehr", club: "FC Winterthur" },
  { id: "p185", name: "Yoan Severin", category: "Abwehr", club: "Servette FC" },
  { id: "p186", name: "Andrejs Ciganiks", category: "Abwehr", club: "Luzern" },
  { id: "p187", name: "Jérémy Frick", category: "Tor", club: "Servette FC" },
  { id: "p188", name: "Maximilian Ullmann", category: "Abwehr", club: "Grasshopper" },
  { id: "p189", name: "Hicham Mahou", category: "Abwehr", club: "Lugano" },
  { id: "p190", name: "Houboulang Mendes", category: "Mittelfeld", club: "Servette FC" },
  { id: "p191", name: "Nikolas Muci", category: "Sturm", club: "Grasshopper" },
  { id: "p192", name: "Bryan Okoh", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p193", name: "Andrej Vasovic", category: "Sturm", club: "Luzern" },
  { id: "p194", name: "Dominik Pech", category: "Mittelfeld", club: "Young Boys" },
  { id: "p195", name: "Jahnoah Markelo", category: "Mittelfeld", club: "Zürich" },
  { id: "p196", name: "Elias Maluvunu", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p197", name: "Severin Ottiger", category: "Abwehr", club: "Luzern" },
  { id: "p198", name: "Yan Valery", category: "Abwehr", club: "Young Boys" },
  { id: "p199", name: "Donat Rrudhani", category: "Mittelfeld", club: "Sion" },
  { id: "p200", name: "Roman Buess", category: "Sturm", club: "FC Winterthur" },
  { id: "p201", name: "Michael Frey", category: "Sturm", club: "Grasshopper" },
  { id: "p202", name: "Marin Šotiček", category: "Mittelfeld", club: "Basel" },
  { id: "p203", name: "Giacomo Koloto", category: "Sturm", club: "Basel" },
  { id: "p204", name: "Colin Kleine-Bekel", category: "Abwehr", club: "St. Gallen" },
  { id: "p205", name: "Seydou Traoré", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p206", name: "Ivan Cavaleiro", category: "Sturm", club: "Zürich" },
  { id: "p207", name: "Sergio Córdova", category: "Sturm", club: "Young Boys" },
  { id: "p208", name: "Damian Kelvin", category: "Abwehr", club: "Lugano" },
  { id: "p209", name: "Tanguy Zoukrou", category: "Abwehr", club: "Young Boys" },
  { id: "p210", name: "Ezgjan Alioski", category: "Mittelfeld", club: "Lugano" },
  { id: "p211", name: "Samuel Essende", category: "Sturm", club: "Young Boys" },
  { id: "p212", name: "Loïc Lüthi", category: "Abwehr", club: "FC Winterthur" },
  { id: "p213", name: "Alban Ajdini", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p214", name: "Marvin da Graça", category: "Abwehr", club: "FC Winterthur" },
  { id: "p215", name: "Adrian Leon Barišić", category: "Abwehr", club: "Basel" },
  { id: "p216", name: "Saulo Decarli", category: "Abwehr", club: "Grasshopper" },
  { id: "p217", name: "Mihailo Stevanovic", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p218", name: "Dorian Paloschi", category: "Abwehr", club: "Grasshopper" },
  { id: "p219", name: "Diego Besio", category: "Sturm", club: "St. Gallen" },
  { id: "p220", name: "Julien Duranville", category: "Mittelfeld", club: "Basel" },
  { id: "p221", name: "Levin Winkler", category: "Mittelfeld", club: "Luzern" },
  { id: "p222", name: "Salifou Diarrassouba", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p223", name: "Ryan Andrews", category: "Abwehr", club: "Young Boys" },
  { id: "p224", name: "Sebastian Walker", category: "Abwehr", club: "Zürich" },
  { id: "p225", name: "Chris Kablan", category: "Abwehr", club: "Zürich" },
  { id: "p226", name: "Juan Perea", category: "Sturm", club: "Zürich" },
  { id: "p227", name: "Stefan Bukinac", category: "Abwehr", club: "Young Boys" },
  { id: "p228", name: "Theo Bergvall", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p229", name: "Valon Berisha", category: "Mittelfeld", club: "Zürich" },
  { id: "p230", name: "Rhodri Smith", category: "Abwehr", club: "FC Winterthur" },
  { id: "p231", name: "Thomas Lopes", category: "Mittelfeld", club: "Servette FC" },
  { id: "p232", name: "Winsley Boteli", category: "Sturm", club: "Sion" },
  { id: "p233", name: "Alexis Antunes", category: "Mittelfeld", club: "Servette FC" },
  { id: "p234", name: "Théo Magnin", category: "Abwehr", club: "Servette FC" },
  { id: "p235", name: "Matteo Mantini", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p236", name: "Becir Omeragic", category: "Abwehr", club: "Basel" },
  { id: "p237", name: "Anthony Baron", category: "Mittelfeld", club: "Servette FC" },
  { id: "p238", name: "Lee Youngjun", category: "Sturm", club: "Grasshopper" },
  { id: "p239", name: "Emanuel Tsimba", category: "Sturm", club: "Grasshopper" },
  { id: "p240", name: "Moussa Cissé", category: "Abwehr", club: "Basel" },
  { id: "p241", name: "Malek Ishuayed", category: "Mittelfeld", club: "Servette FC" },
  { id: "p242", name: "Loun Srdanovic", category: "Abwehr", club: "Servette FC" },
  { id: "p243", name: "Mirlind Kryeziu", category: "Abwehr", club: "FC Winterthur" },
  { id: "p244", name: "Allan Arigoni", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p245", name: "Moritz Broschinski", category: "Sturm", club: "Basel" },
  { id: "p246", name: "Enzo Kana-Biyik", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p247", name: "Dario Ulrich", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p248", name: "Nevio Di Giusto", category: "Mittelfeld", club: "Zürich" },
  { id: "p249", name: "Milan Rodić", category: "Abwehr", club: "Zürich" },
  { id: "p250", name: "Jorge Segura", category: "Abwehr", club: "Zürich" },
  { id: "p251", name: "Franck Surdez", category: "Mittelfeld", club: "Sion" },
  { id: "p252", name: "Giotto Morandi", category: "Mittelfeld", club: "Servette FC" },
  { id: "p253", name: "Mattia Bottani", category: "Mittelfeld", club: "Lugano" },
  { id: "p254", name: "Ablie Jallow", category: "Mittelfeld", club: "Servette FC" },
  { id: "p255", name: "Ledjan Sahitaj", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p256", name: "Téo Allix", category: "Abwehr", club: "Servette FC" },
  { id: "p257", name: "Noah Rupp", category: "Mittelfeld", club: "Thun" },
  { id: "p258", name: "Ousmane Doumbia", category: "Mittelfeld", club: "Lugano" },
  { id: "p259", name: "Malamine Efekele", category: "Sturm", club: "St. Gallen" },
  { id: "p260", name: "Brian Beyer", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p261", name: "Mirko Salvi", category: "Tor", club: "Basel" },
  { id: "p262", name: "Corsin Konietzke", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p263", name: "Christian Gomis", category: "Sturm", club: "FC Winterthur" },
  { id: "p264", name: "Ebrima Colley", category: "Mittelfeld", club: "Young Boys" },
  { id: "p265", name: "Amir Abrashi", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p266", name: "Ayman El Wafi", category: "Abwehr", club: "Lugano" },
  { id: "p267", name: "Calixte Ligue", category: "Abwehr", club: "Zürich" },
  { id: "p268", name: "Zachary Brault-Guillard", category: "Abwehr", club: "Lugano" },
  { id: "p269", name: "Dominik Franke", category: "Abwehr", club: "Thun" },
  { id: "p270", name: "Neil Volken", category: "Abwehr", club: "Zürich" },
  { id: "p271", name: "Olivier Mambwa", category: "Abwehr", club: "Young Boys" },
  { id: "p272", name: "Albert Vallci", category: "Abwehr", club: "St. Gallen" },
  { id: "p273", name: "Selmin Hodza", category: "Abwehr", club: "Zürich" },
  { id: "p274", name: "Dion Kacuri", category: "Mittelfeld", club: "Basel" },
  { id: "p275", name: "Sinan Karweina", category: "Sturm", club: "Luzern" },
  { id: "p276", name: "Shkelqim Vladi", category: "Sturm", club: "St. Gallen" },
  { id: "p277", name: "Théo Bouchlarhem", category: "Mittelfeld", club: "Sion" },
  { id: "p278", name: "Nino Weibel", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p279", name: "Jeremy Agbonifo", category: "Mittelfeld", club: "Basel" },
  { id: "p280", name: "Gaël Ondoua", category: "Mittelfeld", club: "Servette FC" },
  { id: "p281", name: "Mohamed Bangoura", category: "Mittelfeld", club: "Zürich" },
  { id: "p282", name: "Daniel Ihendu", category: "Abwehr", club: "Zürich" },
  { id: "p283", name: "Noë Dussenne", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p284", name: "Lukas Watkowiak", category: "Tor", club: "St. Gallen" },
  { id: "p285", name: "Mamadou Kaly Sene", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p286", name: "Keyan Varela", category: "Mittelfeld", club: "Servette FC" },
  { id: "p287", name: "Vasilije Janjicic", category: "Mittelfeld", club: "Thun" },
  { id: "p288", name: "Sascha Britschgi", category: "Abwehr", club: "Luzern" },
  { id: "p289", name: "Ismajl Beka", category: "Abwehr", club: "Grasshopper" },
  { id: "p290", name: "Furkan Dursun", category: "Sturm", club: "Thun" },
  { id: "p291", name: "Tiemoko Ouattara", category: "Sturm", club: "St. Gallen" },
  { id: "p292", name: "Elias Pihlström", category: "Sturm", club: "Lugano" },
  { id: "p293", name: "Francis Momoh", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p294", name: "Leandro Maksutaj", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p295", name: "Willem Geubbels", category: "Sturm", club: "St. Gallen" },
  { id: "p296", name: "Hamza Abdallah", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p297", name: "Loris Giandomenico", category: "Abwehr", club: "Grasshopper" },
  { id: "p298", name: "Joel Ruiz", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p299", name: "Zachary Athekame", category: "Abwehr", club: "Young Boys" },
  { id: "p300", name: "Arlet Zé", category: "Mittelfeld", club: "Basel" },
  { id: "p301", name: "Dircssi Ngonzo", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p302", name: "Tim Spycher", category: "Tor", club: "Thun" },
  { id: "p303", name: "Lamine Diack", category: "Mittelfeld", club: "Sion" },
  { id: "p304", name: "Rhodri Smith", category: "Abwehr", club: "Young Boys" },
  { id: "p305", name: "Ahmed Kendouci", category: "Mittelfeld", club: "Lugano" },
  { id: "p306", name: "Marvin Akahomen", category: "Abwehr", club: "Basel" },
  { id: "p307", name: "Stephan Ambrosius", category: "Abwehr", club: "St. Gallen" },
  { id: "p308", name: "Maxime Dubosson", category: "Abwehr", club: "Sion" },
  { id: "p309", name: "Jamie Atangana", category: "Sturm", club: "Servette FC" },
  { id: "p310", name: "Maksim Paskotši", category: "Abwehr", club: "Grasshopper" },
  { id: "p311", name: "João Carbone", category: "Mittelfeld", club: "Lugano" },
  { id: "p312", name: "Mardochee Miguel", category: "Mittelfeld", club: "Servette FC" },
  { id: "p313", name: "Marc Gutbub", category: "Mittelfeld", club: "Thun" },
  { id: "p314", name: "Souleymane N'Diaye", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p315", name: "Anton Kade", category: "Mittelfeld", club: "Basel" },
  { id: "p316", name: "Rodolfo Lippo", category: "Abwehr", club: "Lausanne-Sport" },
  { id: "p317", name: "Oscar Renovales", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p318", name: "Nevio Scherrer", category: "Sturm", club: "St. Gallen" },
  { id: "p319", name: "Claudio Cassano", category: "Mittelfeld", club: "Lugano" },
  { id: "p320", name: "Sekou Koné", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p321", name: "Enoch Owusu", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p322", name: "Nico Rissi", category: "Abwehr", club: "Grasshopper" },
  { id: "p323", name: "Alexandre Parsemain", category: "Sturm", club: "Lugano" },
  { id: "p324", name: "Tomás Verón Lupi", category: "Sturm", club: "Grasshopper" },
  { id: "p325", name: "Pantaleo Creti", category: "Abwehr", club: "Grasshopper" },
  { id: "p326", name: "Sandro Wyss", category: "Mittelfeld", club: "Luzern" },
  { id: "p327", name: "Kevin Carlos", category: "Sturm", club: "Basel" },
  { id: "p328", name: "Dominik Papic", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p329", name: "Denis Sahin", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p330", name: "Marquinhos Cipriano", category: "Abwehr", club: "Sion" },
  { id: "p331", name: "Muhanad Al Saad", category: "Mittelfeld", club: "Lausanne-Sport" },
  { id: "p332", name: "Lisandru Tramoni", category: "Mittelfeld", club: "Zürich" },
  { id: "p333", name: "Thomas Castella", category: "Tor", club: "Lausanne-Sport" },
  { id: "p334", name: "Christian Fopossi", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p335", name: "Nicolas Glaus", category: "Tor", club: "Grasshopper" },
  { id: "p336", name: "Antonio Spagnoli", category: "Tor", club: "FC Winterthur" },
  { id: "p337", name: "Mauricio Willimann", category: "Abwehr", club: "Luzern" },
  { id: "p338", name: "Łukasz Łakomy", category: "Mittelfeld", club: "Young Boys" },
  { id: "p339", name: "Kaio Eduardo", category: "Sturm", club: "Basel" },
  { id: "p340", name: "Sascha Meyer", category: "Sturm", club: "Luzern" },
  { id: "p341", name: "Tobias Okafor", category: "Abwehr", club: "FC Winterthur" },
  { id: "p342", name: "Carmine Chiappetta", category: "Sturm", club: "FC Winterthur" },
  { id: "p343", name: "Adrien Llukes", category: "Mittelfeld", club: "Sion" },
  { id: "p344", name: "Betim Fazliji", category: "Abwehr", club: "St. Gallen" },
  { id: "p345", name: "Finn van Breemen", category: "Abwehr", club: "Basel" },
  { id: "p346", name: "Demis Fiechter", category: "Sturm", club: "Grasshopper" },
  { id: "p347", name: "Damien Odera", category: "Sturm", club: "Zürich" },
  { id: "p348", name: "Konrad De La Fuente", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p349", name: "Anton Miranchuk", category: "Mittelfeld", club: "Sion" },
  { id: "p350", name: "Emmanuel Essiam", category: "Mittelfeld", club: "FC Winterthur" },
  { id: "p351", name: "Layton Stewart", category: "Sturm", club: "Thun" },
  { id: "p352", name: "Basil Stillhart", category: "Abwehr", club: "FC Winterthur" },
  { id: "p353", name: "Yannick Bettkober", category: "Abwehr", club: "Grasshopper" },
  { id: "p354", name: "Jordi Quintillà", category: "Mittelfeld", club: "St. Gallen" },
  { id: "p355", name: "Filip Ugrinic", category: "Sturm", club: "Young Boys" },
  { id: "p356", name: "Erblin Sadikaj", category: "Abwehr", club: "Luzern" },
  { id: "p357", name: "Ashvin Balaruban", category: "Abwehr", club: "Thun" },
  { id: "p358", name: "Antonio Verinac", category: "Sturm", club: "St. Gallen" },
  { id: "p359", name: "Tiemoko Ouattara", category: "Sturm", club: "Servette FC" },
  { id: "p360", name: "Emanuel Tsimba", category: "Sturm", club: "Young Boys" },
  { id: "p361", name: "Leart Kabashi", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p362", name: "Vincent Nvendo Ferrier", category: "Sturm", club: "Zürich" },
  { id: "p363", name: "Eliano Guido", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p364", name: "Sambou Camara", category: "Abwehr", club: "FC Winterthur" },
  { id: "p365", name: "Kevin Csoboth", category: "Sturm", club: "St. Gallen" },
  { id: "p366", name: "Ilija Maslarov", category: "Mittelfeld", club: "Lugano" },
  { id: "p367", name: "Evan Senaya", category: "Sturm", club: "Basel" },
  { id: "p368", name: "Gabriel González", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p369", name: "Benjamin Kabeya Muteba", category: "Abwehr", club: "Young Boys" },
  { id: "p370", name: "Andrew Lachhab", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p371", name: "Din Ramić", category: "Sturm", club: "Zürich" },
  { id: "p372", name: "Pirosch Fischer", category: "Sturm", club: "Zürich" },
  { id: "p373", name: "Mio Zimmermann", category: "Mittelfeld", club: "Luzern" },
  { id: "p374", name: "Demir Xhemalija", category: "Mittelfeld", club: "Luzern" },
  { id: "p375", name: "Adam Ilic", category: "Mittelfeld", club: "Thun" },
  { id: "p376", name: "Aaron Tchamda", category: "Mittelfeld", club: "Zürich" },
  { id: "p377", name: "Agon Rexhaj", category: "Sturm", club: "Basel" },
  { id: "p378", name: "Ryan Kessler", category: "Abwehr", club: "Sion" },
  { id: "p379", name: "Jill Stiel", category: "Mittelfeld", club: "Zürich" },
  { id: "p380", name: "Dinis Rodrigues", category: "Sturm", club: "Sion" },
  { id: "p381", name: "Gjan Ajdin", category: "Mittelfeld", club: "Lugano" },
  { id: "p382", name: "Gian Stork", category: "Abwehr", club: "Zürich" },
  { id: "p383", name: "Nahom Tesfom", category: "Mittelfeld", club: "Grasshopper" },
  { id: "p384", name: "Samuele Bengondo", category: "Sturm", club: "Grasshopper" },
  { id: "p385", name: "Alonzo Vincent", category: "Mittelfeld", club: "Servette FC" },
  { id: "p386", name: "Ibrahim Bah Mendes", category: "Sturm", club: "Lausanne-Sport" },
  { id: "p387", name: "Isaiah Okafor", category: "Abwehr", club: "Zürich" },
  { id: "t1", name: "Mauro Lustrinelli", category: "Trainer", club: "FC Thun" },
  { id: "t2", name: "Stephan Lichsteiner", category: "Trainer", club: "FC Basel" },
  { id: "t3", name: "Gerardo Seoane", category: "Trainer", club: "Young Boys" },
  { id: "t4", name: "Mario Frick", category: "Trainer", club: "Luzern" },
  { id: "t5", name: "Didier Tholot", category: "Trainer", club: "Sion" },
  { id: "t6", name: "Patrick Rahmen", category: "Trainer", club: "Winterthur" },
  { id: "t7", name: "Dennis Hediger", category: "Trainer", club: "FC Zürich" },
  { id: "t8", name: "Gerald Scheiblehner", category: "Trainer", club: "Grasshopper Club" },
  { id: "t9", name: "Enrico Maassen", category: "Trainer", club: "St. Gallen" },
  { id: "t10", name: "Mattia Croci-Torti", category: "Trainer", club: "Lugano" },
  { id: "t11", name: "Peter Zeidler", category: "Trainer", club: "Lausanne-Sport" },
  { id: "t12", name: "Jocelyn Gourvennec", category: "Trainer", club: "Servette FC" },
].map(p => {
  const domain = p.club ? CLUB_DOMAIN_MAP[p.club] : undefined;
  return { 
    ...p, 
    category: p.category as PositionCategory,
    clubLogoUrl: (p.club && CLUB_LOGO_MAP[p.club]) ? CLUB_LOGO_MAP[p.club] : undefined,
    clubFallbackUrl: domain ? `https://www.google.com/s2/favicons?domain=${domain}&sz=128` : undefined
  } as Player;
});


export const FORMATIONS: Formation[] = [
  {
    name: "4-4-2",
    positions: [
      { id: "gk", category: "Tor", top: 88, left: 50, label: "TW" },
      { id: "lb", category: "Abwehr", top: 70, left: 15, label: "LV" },
      { id: "lcb", category: "Abwehr", top: 75, left: 38, label: "IV" },
      { id: "rcb", category: "Abwehr", top: 75, left: 62, label: "IV" },
      { id: "rb", category: "Abwehr", top: 70, left: 85, label: "RV" },
      { id: "lm", category: "Mittelfeld", top: 45, left: 15, label: "LM" },
      { id: "lcm", category: "Mittelfeld", top: 50, left: 38, label: "ZM" },
      { id: "rcm", category: "Mittelfeld", top: 50, left: 62, label: "ZM" },
      { id: "rm", category: "Mittelfeld", top: 45, left: 85, label: "RM" },
      { id: "ls", category: "Sturm", top: 20, left: 40, label: "ST" },
      { id: "rs", category: "Sturm", top: 20, left: 60, label: "ST" },
    ],
  },
  {
    name: "4-2-3-1",
    positions: [
      { id: "gk", category: "Tor", top: 88, left: 50, label: "TW" },
      { id: "lb", category: "Abwehr", top: 70, left: 15, label: "LV" },
      { id: "lcb", category: "Abwehr", top: 75, left: 38, label: "IV" },
      { id: "rcb", category: "Abwehr", top: 75, left: 62, label: "IV" },
      { id: "rb", category: "Abwehr", top: 70, left: 85, label: "RV" },
      { id: "ldm", category: "Mittelfeld", top: 55, left: 40, label: "DM" },
      { id: "rdm", category: "Mittelfeld", top: 55, left: 60, label: "DM" },
      { id: "lam", category: "Mittelfeld", top: 35, left: 20, label: "OM" },
      { id: "cam", category: "Mittelfeld", top: 30, left: 50, label: "OM" },
      { id: "ram", category: "Mittelfeld", top: 35, left: 80, label: "OM" },
      { id: "st", category: "Sturm", top: 15, left: 50, label: "ST" },
    ],
  },
  {
    name: "4-3-3",
    positions: [
      { id: "gk", category: "Tor", top: 88, left: 50, label: "TW" },
      { id: "lb", category: "Abwehr", top: 70, left: 15, label: "LV" },
      { id: "lcb", category: "Abwehr", top: 75, left: 38, label: "IV" },
      { id: "rcb", category: "Abwehr", top: 75, left: 62, label: "IV" },
      { id: "rb", category: "Abwehr", top: 70, left: 85, label: "RV" },
      { id: "dm", category: "Mittelfeld", top: 55, left: 50, label: "DM" },
      { id: "lcm", category: "Mittelfeld", top: 40, left: 30, label: "ZM" },
      { id: "rcm", category: "Mittelfeld", top: 40, left: 70, label: "ZM" },
      { id: "lw", category: "Sturm", top: 20, left: 20, label: "LF" },
      { id: "rw", category: "Sturm", top: 20, left: 80, label: "RF" },
      { id: "st", category: "Sturm", top: 15, left: 50, label: "ST" },
    ],
  },
  {
    name: "3-5-2",
    positions: [
      { id: "gk", category: "Tor", top: 88, left: 50, label: "TW" },
      { id: "lcb", category: "Abwehr", top: 75, left: 25, label: "IV" },
      { id: "cb", category: "Abwehr", top: 80, left: 50, label: "IV" },
      { id: "rcb", category: "Abwehr", top: 75, left: 75, label: "IV" },
      { id: "lm", category: "Mittelfeld", top: 50, left: 15, label: "LM" },
      { id: "ldm", category: "Mittelfeld", top: 60, left: 38, label: "DM" },
      { id: "rdm", category: "Mittelfeld", top: 60, left: 62, label: "DM" },
      { id: "rm", category: "Mittelfeld", top: 50, left: 85, label: "RM" },
      { id: "cam", category: "Mittelfeld", top: 40, left: 50, label: "OM" },
      { id: "ls", category: "Sturm", top: 20, left: 40, label: "ST" },
      { id: "rs", category: "Sturm", top: 20, left: 60, label: "ST" },
    ],
  },
  {
    name: "3-4-3", 
    positions: [
      { id: "gk", category: "Tor", top: 88, left: 50, label: "TW" },
      { id: "lcb", category: "Abwehr", top: 75, left: 25, label: "IV" },
      { id: "cb", category: "Abwehr", top: 80, left: 50, label: "IV" },
      { id: "rcb", category: "Abwehr", top: 75, left: 75, label: "IV" },
      { id: "lm", category: "Mittelfeld", top: 55, left: 15, label: "LM" },
      { id: "lcm", category: "Mittelfeld", top: 60, left: 40, label: "ZM" },
      { id: "rcm", category: "Mittelfeld", top: 60, left: 60, label: "ZM" },
      { id: "rm", category: "Mittelfeld", top: 55, left: 85, label: "RM" },
      { id: "lam", category: "Sturm", top: 35, left: 35, label: "OM" },
      { id: "ram", category: "Sturm", top: 35, left: 65, label: "OM" },
      { id: "st", category: "Sturm", top: 15, left: 50, label: "ST" },
    ],
  },
];
